- coding/two_sum/README_en.md
- coding/two_sum/SOLUTION_en.md
- coding/two_sum/meta.yml
- coding/two_sum/starter.c
- coding/two_sum/starter.cpp
- coding/two_sum/starter.go
- coding/two_sum/starter.java
- coding/two_sum/starter.js
- coding/two_sum/starter.py
- coding/two_sum/starter.rb
Add the two-sum problem from Leetcode: https://leetcode.com/problems/two-sum/
> Add two-sum problem

- .github/workflows/generate_coding_json.yml
- Rakefile
[Generating coding JSON action](https://github.com/HackerPen/tech-interview-questions/actions/workflows/generate_coding_json.yml) should be triggered every time a new pull request is merged to change anything under `coding/` directory.
Based on [Github's documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths), `/**` needs to be added to include all files.
> [ADHOC] Fix Github Action

- coding/top_k_frequent_elements/README_en.md
- coding/top_k_frequent_elements/SOLUTION_en.md
- coding/top_k_frequent_elements/meta.yml
- coding/top_k_frequent_elements/starter.js
- coding/top_k_frequent_elements/starter.py
added top k frequent elements to coding folder.
added javascript and python to solution
> top k freq elements added to coding folder

- coding/find_median_from_data_stream/README_en.md
- coding/find_median_from_data_stream/SOLUTION_en.md
- coding/find_median_from_data_stream/meta.yml
- coding/find_median_from_data_stream/starter.js
- coding/find_median_from_data_stream/starter.py
added 3 approaches in python and javascript for find median from data stream
> added javascript and python solutions for find median from data stream

- Rakefile
> [#14] add validation

- Rakefile
added 2 TODO validation rules
edited exceptions to include file identifier in exceptions
> Add validations

- coding/top_k_frequent_elements/meta.yml
- coding/top_k_frequent_elements/starter.c
- coding/top_k_frequent_elements/starter.cpp
- coding/top_k_frequent_elements/starter.go
- coding/top_k_frequent_elements/starter.java
- coding/top_k_frequent_elements/starter.rb
> top_k_frequent_elements: starter code filled out and meta updated

- coding/three_sum/meta.yml
- coding/three_sum/starter.c
- coding/three_sum/starter.cpp
- coding/three_sum/starter.go
- coding/three_sum/starter.java
- coding/three_sum/starter.rb
> three_sum: starter code filled out and meta updated

- _coding_template/starter.c
- coding/merge_k_sorted_lists/meta.yml
- coding/merge_k_sorted_lists/starter.cpp
- coding/merge_k_sorted_lists/starter.go
- coding/merge_k_sorted_lists/starter.java
- coding/merge_k_sorted_lists/starter.rb
> merge_k_sorted_lists: starter code filled out and meta updated

- coding/find_median_from_data_stream/meta.yml
- coding/find_median_from_data_stream/starter.c
- coding/find_median_from_data_stream/starter.cpp
- coding/find_median_from_data_stream/starter.go
- coding/find_median_from_data_stream/starter.java
- coding/find_median_from_data_stream/starter.rb
- coding/merge_intervals/meta.yml
- coding/merge_intervals/starter.c
- coding/merge_intervals/starter.cpp
- coding/merge_intervals/starter.go
- coding/merge_intervals/starter.java
- coding/merge_intervals/starter.rb
> Merge intervals edit

- coding/find_median_from_data_stream/starter.c
> find_median_from_data_stream: starter code filled out and meta updated

- .github/workflows/generate_system_design_json.yml
- .github/workflows/test_system_design_json.yml
- README.md
- Rakefile
- _system_design_template/README_en.md
- _system_design_template/SOLUTION_en.md
- _system_design_template/meta.yml
- coding.json
- system_design/url_shortening/README_en.md
- system_design/url_shortening/SOLUTION_en.md
- system_design/url_shortening/meta.yml
> Add system design template and first question

- coding/spiral_matrix/README_en.md
- coding/spiral_matrix/SOLUTION_en.md
- coding/spiral_matrix/meta.yml
- coding/spiral_matrix/starter.c
- coding/spiral_matrix/starter.cpp
- coding/spiral_matrix/starter.go
- coding/spiral_matrix/starter.java
- coding/spiral_matrix/starter.js
- coding/spiral_matrix/starter.py
- coding/spiral_matrix/starter.rb
added spiral matrix to coding problems
unsure how you'd want to do this, but for this problem, a picture may be helpful to visualize the traversal
> spiral matrix added

- coding/rotate_matrix/README_en.md
- coding/rotate_matrix/SOLUTION_en.md
- coding/rotate_matrix/meta.yml
- coding/rotate_matrix/starter.c
- coding/rotate_matrix/starter.cpp
- coding/rotate_matrix/starter.go
- coding/rotate_matrix/starter.java
- coding/rotate_matrix/starter.js
- coding/rotate_matrix/starter.py
- coding/rotate_matrix/starter.rb
added rotate matrix coding problem
> rotate_matrix added

- coding/word_search/README_en.md
- coding/word_search/SOLUTION_en.md
- coding/word_search/meta.yml
- coding/word_search/starter.c
- coding/word_search/starter.cpp
- coding/word_search/starter.go
- coding/word_search/starter.java
- coding/word_search/starter.js
- coding/word_search/starter.py
- coding/word_search/starter.rb
added python and javascript solutions to word search
> added word search coding problem

- Rakefile
> add uniqueness check for system design

- coding/meeting_rooms/README_en.md
- coding/meeting_rooms/SOLUTION_en.md
- coding/meeting_rooms/meta.yml
- coding/meeting_rooms/starter.c
- coding/meeting_rooms/starter.cpp
- coding/meeting_rooms/starter.go
- coding/meeting_rooms/starter.java
- coding/meeting_rooms/starter.js
- coding/meeting_rooms/starter.py
- coding/meeting_rooms/starter.rb
added meeting rooms
javascript, python, java solutions
> added meeting_rooms coding question

- .github/workflows/close_stale_issues_and_prs.yml
Address failure runs: [link](https://github.com/HackerPen/tech-interview-questions/actions/workflows/close_stale_issues_and_prs.yml)
> fix indentation

- coding/insert_interval/README_en.md
- coding/insert_interval/SOLUTION_en.md
- coding/insert_interval/meta.yml
- coding/insert_interval/starter.c
- coding/insert_interval/starter.cpp
- coding/insert_interval/starter.go
- coding/insert_interval/starter.java
- coding/insert_interval/starter.js
- coding/insert_interval/starter.py
- coding/insert_interval/starter.rb
added insert interval in javascript, python
> added insert interval coding question

- system_design/online_chat/README_en.md
- system_design/online_chat/SOLUTION_en.md
- system_design/online_chat/meta.yml
> add online chat SD question

- system_design/news_feed/SOLUTION_en.md
- system_design/spending_tracker/README_en.md
- system_design/spending_tracker/SOLUTION_en.md
- system_design/spending_tracker/meta.yml
- system_design/url_shortening/SOLUTION_en.md
- system_design/web_crawler/SOLUTION_en.md
> add spending tracker question

- coding/find_minimum_in_rotated_sorted_array/README_en.md
- coding/find_minimum_in_rotated_sorted_array/SOLUTION_en.md
- coding/find_minimum_in_rotated_sorted_array/meta.yml
- coding/find_minimum_in_rotated_sorted_array/starter.c
- coding/find_minimum_in_rotated_sorted_array/starter.cpp
- coding/find_minimum_in_rotated_sorted_array/starter.go
- coding/find_minimum_in_rotated_sorted_array/starter.java
- coding/find_minimum_in_rotated_sorted_array/starter.js
- coding/find_minimum_in_rotated_sorted_array/starter.py
- coding/find_minimum_in_rotated_sorted_array/starter.rb
added javascript, python, java solutions
> added find minimum in rotated sorted array

- coding/search_in_rotated_sorted_array/README_en.md
- coding/search_in_rotated_sorted_array/SOLUTION_en.md
- coding/search_in_rotated_sorted_array/meta.yml
- coding/search_in_rotated_sorted_array/starter.c
- coding/search_in_rotated_sorted_array/starter.cpp
- coding/search_in_rotated_sorted_array/starter.go
- coding/search_in_rotated_sorted_array/starter.java
- coding/search_in_rotated_sorted_array/starter.js
- coding/search_in_rotated_sorted_array/starter.py
- coding/search_in_rotated_sorted_array/starter.rb
java, javascript, python solutinos added
> added search in rotated sorted array to coding problems

- coding/contains_duplicate/README_en.md
- coding/contains_duplicate/SOLUTION_en.md
- coding/contains_duplicate/meta.yml
- coding/contains_duplicate/starter.c
- coding/contains_duplicate/starter.cpp
- coding/contains_duplicate/starter.go
- coding/contains_duplicate/starter.java
- coding/contains_duplicate/starter.js
- coding/contains_duplicate/starter.py
- coding/contains_duplicate/starter.rb
added java, python, javascript solutions
> added contains duplicate coding question

- coding/number_of_islands/README_en.md
- coding/number_of_islands/SOLUTION_en.md
- coding/number_of_islands/meta.yml
- coding/number_of_islands/starter.c
- coding/number_of_islands/starter.cpp
- coding/number_of_islands/starter.go
- coding/number_of_islands/starter.java
- coding/number_of_islands/starter.js
- coding/number_of_islands/starter.py
- coding/number_of_islands/starter.rb
added javascript and python solutions
> added number of islands

- coding/coin_change/README_en.md
- coding/coin_change/SOLUTION_en.md
- coding/coin_change/meta.yml
- coding/coin_change/starter.c
- coding/coin_change/starter.cpp
- coding/coin_change/starter.go
- coding/coin_change/starter.java
- coding/coin_change/starter.js
- coding/coin_change/starter.py
- coding/coin_change/starter.rb
> add coin change problem

- coding/unique_paths/README_en.md
- coding/unique_paths/SOLUTION_en.md
- coding/unique_paths/meta.yml
- coding/unique_paths/starter.c
- coding/unique_paths/starter.cpp
- coding/unique_paths/starter.go
- coding/unique_paths/starter.java
- coding/unique_paths/starter.js
- coding/unique_paths/starter.py
- coding/unique_paths/starter.rb
added solutions in python, java, javascript
> added unique paths coding question

- system_design/ride-share/README_en.md
- system_design/ride-share/SOLUTION_en.md
- system_design/ride-share/meta.yml
> add ride share SD question

- coding/reverse_linked_list/README_en.md
- coding/reverse_linked_list/SOLUTION_en.md
- coding/reverse_linked_list/meta.yml
- coding/reverse_linked_list/starter.c
- coding/reverse_linked_list/starter.cpp
- coding/reverse_linked_list/starter.go
- coding/reverse_linked_list/starter.java
- coding/reverse_linked_list/starter.js
- coding/reverse_linked_list/starter.py
- coding/reverse_linked_list/starter.rb
added python, java, javascript solutions
> added reverse linked list coding question

- coding/merge_two_sorted_linked_lists/README_en.md
- coding/merge_two_sorted_linked_lists/SOLUTION_en.md
- coding/merge_two_sorted_linked_lists/meta.yml
- coding/merge_two_sorted_linked_lists/starter.c
- coding/merge_two_sorted_linked_lists/starter.cpp
- coding/merge_two_sorted_linked_lists/starter.go
- coding/merge_two_sorted_linked_lists/starter.java
- coding/merge_two_sorted_linked_lists/starter.js
- coding/merge_two_sorted_linked_lists/starter.py
- coding/merge_two_sorted_linked_lists/starter.rb
added python, java, javascript solutions
> added merge 2 sorted linked lists coding question

- system_design/photo_sharing/README_en.md
- system_design/photo_sharing/SOLUTION_en.md
- system_design/photo_sharing/meta.yml
> add photo sharing SD question

- coding/longest_substring_without_repeating_characters/README_en.md
- coding/longest_substring_without_repeating_characters/SOLUTION_en.md
- coding/longest_substring_without_repeating_characters/meta.yml
- coding/longest_substring_without_repeating_characters/starter.c
- coding/longest_substring_without_repeating_characters/starter.cpp
- coding/longest_substring_without_repeating_characters/starter.go
- coding/longest_substring_without_repeating_characters/starter.js
- coding/longest_substring_without_repeating_characters/starter.py
- coding/longest_substring_without_repeating_characters/starter.rb
> add longest substring

- coding/copy_graph/README_en.md
- coding/copy_graph/SOLUTION_en.md
- coding/copy_graph/meta.yml
- coding/copy_graph/starter.js
- coding/copy_graph/starter.py
Creates Copy graph question
@marshallshen Would love a review!
> Creates copy-graph question

- coding/merge_two_sorted_linked_lists/README_en.md
> Fix typo in "Merge two sorted linked lists" 
